### PR TITLE
Add new fields and const to allow a recurring authorisation request

### PR DESCRIPTION
**Pull request by lbailly**

### CODE REVIEW

**Comment by lbailly** [comment]
Hello @zhutik, a lint issue again. What do you prefer for the naming of const ?

Thks,

Ludo

**Comment by zhutik** [comment]
@lbailly Hi, I've setup low threshold for code linter, so it can suggest standards that are used in most of other packages and language itself. I suggest renaming constants from capital to CamelCaps, f.e. ```SHOPPER_INTERACTION_CONTAUTH``` should be ```ShopperInteraction ContAuth```

**Comment by lbailly** [comment]
Hi @zhutik, ok to rename existings ONECLICK and RECURRING consts in camel caps too ?

**Comment by zhutik** [comment]
@lbailly yes, let's rename them. We need to find a better way in future to deal with such enum values.

**Pull request closed without merging**
