### PR TITLE
add NewStringBool

### PR DESCRIPTION
**Pull request by sywesk**
Add the NewStringBool function 👍 

Sorry for the previous PR, i messed up somehow. :/

### CODE REVIEW

**Comment by sywesk** [comment]
@zhutik 

`
boolean.go:12:28: exported func NewStringBool returns unexported type *adyen.stringBool, which can be annoying to use
Found 2 lint suggestions; failing.
`

**Comment by zhutik** [comment]
Seems like code quality check tool suggests to export stringBool type to avoid confusion in a client apps. So let's also do that.

**Comment by sywesk** [comment]
The build is failing on what looks like an empty environment variable `$COVERALLS_TOKEN`

```
$ goveralls -service=travis-ci -coverprofile=gover.coverprofile -repotoken $COVERALLS_TOKEN
flag needs an argument: -repotoken
```

**Comment by zhutik** [comment]
@sywesk yeah, this variable is not exposed for repo non-masters. I added the new key that would be open. Build restarted, should fine soon. Sorry for inconveniences.

**Comment by sywesk** [comment]
Nah don't worry 😄 thank you for helping me with this build process

**Pull request merged**
