### PR TITLE
Add random and company name parts of production urls

### PR DESCRIPTION
**Pull request by codingconcepts**
Righto sir, that's all checked in.  Let me know what you think!

### CODE REVIEW

**Review by zhutik — APPROVED** [review]
LGTM!

One comment: can you please update README file to include how live environment should be used?

**Comment by codingconcepts** [comment]
Ah yes, totally forgot about that bit, sorry!

**Comment by codingconcepts** [comment]
Hey Igor,

I've added the README docs as requested and actually changed how we return Testing and Production configuration.  Let me know what you think!


Cheers,

Rob

**Comment by zhutik** [comment]
Thanks a lot! Merging

**Pull request merged**
