### PR TITLE
Updating API versions

### PR DESCRIPTION
**Pull request by nirajjayant**
As far as I know, the versions are backwards compatible so updating versions of Checkout, Payment and Recurring

### CODE REVIEW

**Comment by nirajjayant** [comment]
@zhutik thanks so much for the library - I've found it very useful! I'm happy to clean up my additions (needed for my workflow) if you want to merge it in master otherwise I can continue to work in my fork and just close this PR?

**Comment by zhutik** [comment]
@nirajjayantbolt Hey! Thanks a lot for your contribution! Please check the codeclimate error in a new file, once it's fixed, I can merge this for sure

**Comment by nirajjayant** [comment]
@zhutik - done! Thanks a bunch :) 
Also sorry for putting a couple things in this PR, I'll create PRs against different branches next time. I think I'm going to add more stuff to Notification -> AdditionalData for fraud related webhooks

**Comment by nirajjayant** [comment]
@zhutik do you mind merging? I'm not sure if I want to migrate over to official library yet since some type checking isn't as strong there

**Comment by zhutik** [comment]
Merging, but please still migrate to the official one! Thanks a lot!

**Pull request merged**
