### PR TITLE
Feature/file count

### PR DESCRIPTION
**Pull request by codingconcepts**
Hey Igor,

Sorry for the large checkin here, I started by moving some types into a single file because the vertical space was meaning I was getting a bit lost in the code and I ended up making a few more modifications as I'm beginning to plumb this into a service! :)

Cheers,

Rob

### CODE REVIEW

**Comment by zhutik** [comment]
@codingconcepts I really like improvements!

One question that I have is merging all types into one file `types.go`. Before, I checked other go packages, and somehow I like the idea of splitting meaningful API entities into different files:

f.e. https://github.com/stripe/stripe-go, https://github.com/drone/drone/tree/master/model and so on. 

This approach is also correlating with documentation https://docs.adyen.com/developers/api-reference/payments-api 

maybe we can try to do a split based on API functional methods like:
- payment (authorise, 3d, e.t.c)
- modification (capture, cancel, refund e.t.c) (https://docs.adyen.com/developers/payment-modifications)
- notifications
- recurring 
- hosted payment pages (directory lookup, hpp redirects)

please let me know, what do you think

**Review by zhutik — COMMENTED** [review]
@codingconcepts I really like improvements!

One question that I have is merging all types into one file types.go. Before, I checked other go packages, and somehow I like the idea of splitting meaningful API entities into different files:

f.e. https://github.com/stripe/stripe-go, https://github.com/drone/drone/tree/master/model and so on.

This approach is also correlating with documentation https://docs.adyen.com/developers/api-reference/payments-api

maybe we can try to do a split based on API functional methods like:

- payment (authorise, 3d, e.t.c)
- modification (capture, cancel, refund e.t.c) (https://docs.adyen.com/developers/payment-modifications)
- notifications
- recurring
- hosted payment pages (directory lookup, hpp redirects)

please let me know, what do you think

**Comment by codingconcepts** [comment]
Evening sir!  Thanks for getting back to me!  Yeah, I like the idea of splitting files into their functional groups, my moving into a single file was pretty aggressive :P

A “model” (or similar) directly might also be a good idea perhaps?  Your call obviously!

Either way, I completely agree, something less aggressive than a single-file solution would be better here.


Cheers!

Rob

**Comment by zhutik** [comment]
@codingconcepts 

I propose example structure like this:
...
payment.go (structs for payment entities like authroze, 3d, recurring e.t.c)
payment_gateway.go (functional calls to an API)
payment_test.go
payment_gateway_test.go (if possible)
...

and so on for modification, notification, local_payment (https://docs.adyen.com/developers/ecommerce-integration/local-payment-methods , directory_lookup, hpp redirect and so on)

Thanks!

**Comment by codingconcepts** [comment]
Yeah that sounds sensible to me.  Keep the types

**Comment by codingconcepts** [comment]
Yeah, that seems sensible to me.  Keep the types close to where they’re being used.

Would you like me to do this now, or did you want to make the change?


Cheers Igor :)

Rob

**Comment by zhutik** [comment]
Can you please do a change? 

Thanks!

**Comment by zhutik** [comment]
Can you please resolve a conflict, I will merge a change and do a split afterward as a separate request

**Review by codingconcepts — COMMENTED** [review]
As the PR author, I can't approve but this LGTM :)

**Pull request merged**
